name: Red Badger Martian Robots .NET Build & Test Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore ./RB.MartianRobots.sln

    - name: Build solution
      run: dotnet build ./RB.MartianRobots.sln --configuration Release --no-restore

    - name: Run unit tests
      run: dotnet test ./RB.MartianRobots.sln --configuration Release --no-build --verbosity normal
